# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FUIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FUIDemo
  pod 'FRCategories', '0.0.6'
  pod 'FRCategories', '0.0.6'

end
